### ISSUE TITLE
Map the clinical trial accrual data to the Cancer In Focus high-level cancer types based on the same logic used for the NM tumor registry volume.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#184]
NOTIS does not support mapping its disease sites to histologies.  The long-term solution will be to support that.  A ticket will be created in NOTIS-RAILS tracker.  In the interim, we will have to manually map the NOTIS disease site names for HEME cancers to histologies to make the mapping logic work.

**Comment by mgurley** [comment]
Add the support in NOTIS for multiple namespace mappings for clinical trails accrual:

- NCI Mapping
- NM Tumory Registry Mapping

**Comment by PerifanosPrometheus** [comment]
Added column with disease site to notis accrual. Now needing to implement the mapping.

**Comment by PerifanosPrometheus** [comment]
Notes from COE meeting:
- Waiting to validate if we need to use SEER mapping/NCI ICD-O-3 to cancer mapping.
- Notis implemented the change to support NCI ICD-O-3 to cancer mapping

**Comment by PerifanosPrometheus** [comment]
Confirm with CTO that for the NOTIS accrual we can use the same dataset used for the dashboard sent out to disease teams every month.

**Comment by PerifanosPrometheus** [comment]
Daniel is obtaining this data from the report called 'geodata'. We can use that and update the disease site mapping on there.

At the same time, it's probably consolidating both the accrual provided to daniel(via geodata) and the dataflow used to powerBI dashboard for disease team accruals into a single code rather than maintaining two separate ones.
