### ISSUE TITLE
Screening rates request from COE.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#23]
From Tarneka:

"We are trying to get a rough estimate of the screening rate for eligible patients at NM. Is it possible to pull the screening numbers and create a screening rate for the eligible patient population for each screening category? I’ve attached all of the screening codes for Cervical, Colorectal, Prostate and Breast Cancer Screening. Let me know if that makes sense."
[Copy of ScreeningCodes.xlsx](https://github.com/NU-QDSC/cancer-informatics/files/11544096/Copy.of.ScreeningCodes.xlsx)

**Comment by PerifanosPrometheus** [comment]
Development Notes:

After discussions with @mgurley and @neelimakatam, I am now modifying the sql to break down screening rates by gender and year.

Breaking down by gender is straightforward, breaking down the information by year requires some additional conversations. 

Indeed, there are a couple of questions that need to be answered before we can provide the historical year by year data. Here are the questions:

- Should screening rates be specific to each year? 
   - For example, let's assume a patient is screened in 2021 but not in 2022. Should the screening that was performed in 2021 count towards the 2022 count as well? 
     - My guess is no, but I would like to discuss that.

- What determines when a patient becomes eligible and should be counted as an NM/NU patient? Is it when the patient record is created? 
   - If so, this info is not readily stored in the NM_BI view table for patients.
   - Potential solution 1: using the date of creation of the record in the source system, this is not ideal since it would mean having to develop a query/logic for every unique source system(cerner etc.) to find their creation date.
   - Potential Solution 2: Looking at first encounter date by patient. This is also not ideal since it involves querying every encounter for all patients to find their first one. 
   - Alternative option: only provide rates for the past year.

- How should deceased patients be counted in this measure? 
   - Thinking of the following:
      -  Once a patient dies, he becomes ineligible starting the following year.
      - If a patient is screened in a given year when he/she/they was eligible and then dies the same year. He/she/they shall be counted for that year but not future years.
