### ISSUE TITLE
Address request from Melissa Simon on Triple Negative Breast Cancer and the catchment are.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#240]

**Comment by PerifanosPrometheus** [comment]
Meeting from COE:

Create a new extract containing volume of triple negative breast cancer patients from the tumor registry:
-create request for triple negative breast cancer extract
-create in qdsc tracker


--volume rather than how many facilities a patient has been seen
-patient
-tumor id
-year of diagnosis
-county
