### ISSUE TITLE
Support the association of disease teams with disease sites in NOTIS.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#328]
Use this in the Disease Teams reports.  #122

**Comment by PerifanosPrometheus** [comment]
Since we often want to display accrual/patient population data by disease team and the accrual/population data is generally mapped to disease sites, it would be nice to create a mapping between disease sites and disease teams. For example:
Head & Neck Disease team -> Head & Neck Disease site patients
...

Hopefully most mapping are as straightforward as the above

**Comment by mgurley** [comment]
Bring it up at the next NOTIS user meeting.

**Comment by fanglinnw** [comment]
- [ ] Run a report to see if there are clear mapping patterns for certain disease teams and the disease sites on accruals.
- [ ] Present the result to Catie for review
- [ ] Once approved, store the mapping in NOTIS

**Comment by mgurley** [comment]
10/31/2024 Anlil explained new mapping logic.  NOTIS team will incorporate obvious mappings into NOTIS and send to @PerifanosPrometheus for development into Disease team reports.  Waiting on CTO to make decisions on edge cases.
