### ISSUE TITLE
Find out if we can deploy the Cancer In Focus Shiny application locally on premise for free.

### ISSUE THREAD

**Issue by mgurley** [NU-QDSC/cancer-informatics#56]
Reach out to the University of Kentucky for guidance on deploying the Cancer In Focus Shiny application locally on premise for free.  See Shiny deployment/pricing models here:
https://posit.co/products/open-source/shinyserver/

**Comment by Danton6** [comment]
Hi Michael, I reached out to Todd yesterday and this is the breakdown he gave me:
•	The cheapest way is to set up your own local Shiny server. This is free, but require time on the IT side at your institution to get going (Northwestern may already local Shiny servers set up, which will save time). 
•	The best but most expensive way is by using Posit (RStudio) Connect. This is the enterprise solution and makes deployment a breeze. If Northwestern has this, by all means use it, but if they don't you probably won't buy it just for CIF. 
•	The middle ground is by using a paid account on shinyapps.io. This is what we're doing for now as I try to loosen purse string to get Connect. It works fine, but has a startup time for most users because the app will go to sleep when not visited for a set amount of time. This costs about $300/yr for a Pro account.
•	The secret fourth way is to use Docker. We have two centers that have successfully deployed this way, but it's a bit of a pain. They could provide insights on how to make it easier for you if you wanted to go that route

**Comment by mgurley** [comment]
@Danton6 

We will want to go either with your #1 or #4.  #2 is likely unnecessary.  #3 is a no-go.  As we want to be able to control this ourselves behind our NU firewall.  Did you talk to Todd about #4?

**Comment by mgurley** [comment]
We determined to use ShinyProxy.
